spring.application.name=commonService

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/microservice-project
spring.datasource.username=postgres
spring.datasource.password=pratap123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect